### ISSUE TITLE
Order.RequestedLots всегда 0

### ISSUE THREAD

**Issue by dimappik** [TinkoffCreditSystems/invest-openapi-go-sdk#11]
Есть ощущение, что поле RequestedLots для каждого элемента слайса, возвращаемого restClient.Orders(ctx) всегда нулевое.

Если я правильно понимаю, то там должно быть значение, которое указываешь при выставлении заявки через restClient.LimitOrder(...)

**Comment by necryin** [comment]
Похоже на багу на стороне апи. Разбираемся, заведем багу

**Comment by dimappik** [comment]
fixed
