### ISSUE TITLE
Отсутствует averagePositionPrice

### ISSUE THREAD

**Issue by maksim77** [TinkoffCreditSystems/invest-openapi-go-sdk#13]
В структуре `PositionBalance` не хватает полей `averagePositionPrice` и `averagePositionPriceNoNkd`. Соответственно нет возможности узнать итоговую стоимость портфеля.

**Comment by necryin** [comment]
Спасибо! Добавил недостоющие поля

**Comment by NikitaMelnikov** [comment]
@necryin 
Тикет закрываем?

**Comment by maksim77** [comment]
Отлично. Все работает. 
@NikitaMelnikov, может быть стоит добавить в само API поле с НКД? А то посчитать конечно не сложно, но вроде как это базовая информация для облигаций и она может быть доступна и в явном виде.

**Comment by NikitaMelnikov** [comment]
@maksim77 согласен с вами, создадите тикен в основном репозитории? https://github.com/TinkoffCreditSystems/invest-openapi/issues/
