### ISSUE TITLE
Поддержка API версии 20.1

### ISSUE THREAD

**Issue by maksim77** [TinkoffCreditSystems/invest-openapi-go-sdk#17]
Я, конечно понимаю, что релиз вышел полчаса как но тем не менее :)

Вышел новый релиз [OpenAPI 20.1](https://github.com/TinkoffCreditSystems/invest-openapi/releases/tag/20.1)
было бы здорово иметь его поддержку в SDK.

**Comment by necryin** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/releases/tag/v0.4.0
