### ISSUE TITLE
Добавьте тег с версией

### ISSUE THREAD

**Issue by doroginin** [TinkoffCreditSystems/invest-openapi-go-sdk#2]
Добавьте тег с версией `vX.Y.Z` пожалуйста, сейчас в `go.mod` зависимость выглядит вот так:

`github.com/TinkoffCreditSystems/invest-openapi-go-sdk v0.0.0-20191101121044-03b8c86b810e`

**Comment by NikitaMelnikov** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/pull/3
Done
