### ISSUE TITLE
Что должно быть прописано в go.mod

### ISSUE THREAD

**Issue by ILikeGoland** [TinkoffCreditSystems/invest-openapi-go-sdk#21]
Что должно быть прописано в go.mod, чтобы обновления устанавливались без необходимости копировать файлы вручную?

**Comment by triamazikamno** [comment]
Зачем что-то копировать?
`go get -u github.com/TinkoffCreditSystems/invest-openapi-go-sdk`
должно все само обновить и поставить

**Comment by ILikeGoland** [comment]
Ок, сейчас попробую с опцией -u 
Без нее обновление не получилось
