### ISSUE TITLE
Переподключение StreamingClient

### ISSUE THREAD

**Issue by m4ex** [TinkoffCreditSystems/invest-openapi-go-sdk#25]
Пробовал использовать данный SDK, столкнулся с тем что Web Socket может закрываться например в случае временных сетевых проблем. Приложение перестает получать данные. Было бы не плохо чтобы у StreamingClient была опция автоматического переподключения (повторный вызов dialer.Dial при разрыве подключения, наверное раз в какой-то промежуток времени, до успешного подключения). Проблему конечно можно решить на клиентской стороне, но мне кажется, что правильнее  реализовать данную функцию в SDK.

**Comment by necryin** [comment]
Этот SDK скорее низкоуровневый.  Просто переподключение же вам не будет интересно, так как все подписки теряются. Значит надо их еще где-то хранить ну и там дальше много чего кастомного можно придумать

**Comment by m4ex** [comment]
Спасибо за ваш комментарий. Да, вы правы. Тот момент что подписки теряются я упустил. Думаю вопрос можно закрыть. Согласен что переподключение и переподписка в данном случае уместнее на стороне клиентского приложения.
