### ISSUE TITLE
Можно ли удалить ранее выданные токены в случае необходимости?

### ISSUE THREAD

**Issue by mantyr** [TinkoffCreditSystems/invest-openapi-go-sdk#28]
В интерфейсе "Инвестиции->Настройки" списка выданных токенов не обнаружил. 

Возник закономерный вопрос - можно ли увидеть список выданных токенов и можно ли их отменить при такой необходимости?

**Comment by NikitaMelnikov** [comment]
На странице https://id.tinkoff.ru/account вы сможете отозвать выданные токены
