### ISSUE TITLE
Вывод свечей.

### ISSUE THREAD

**Issue by vedmak3** [TinkoffCreditSystems/invest-openapi-go-sdk#33]
https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/blob/3cc3cf4c0da1589ece03a0e5b73ad6a94eabdc7e/examples/main.go#L329

Предлагаю поменять на это
`res, _ := json.Marshal(candles)`
	`println(string(res))`

**Comment by sgaynetdinov** [comment]
@vedmak3 чем текущее решение не устраивает?

**Comment by vedmak3** [comment]
Выводит не json формат, без кавычек.

**Comment by spiritofsim** [comment]
> Выводит не json формат, без кавычек.

Это же просто пример
