### ISSUE TITLE
Возможность получения списка пополнений счета и выводов с него

### ISSUE THREAD

**Issue by spiritofsim** [TinkoffCreditSystems/invest-openapi-go-sdk#34]
В api и примерах не нашел (

**Comment by YuriyIlyin** [comment]
См. Получении информации по операциям
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/

**Comment by ILikeGoland** [comment]
// Получение данных обо всех операциях с деньгами
// Извлекаем через API все (вместо Fig стоит "") операции с деньгами на брокерском счете (Ввод - PayIn / Вывод - PayOut) за последние 24 дня
	oper, err := api.Operations(ctx, sdk.DefaultAccount, time.Now().AddDate(0,0,-24), time.Now(), ""); if err != nil {log.Fatalln(err)}
	s:=[]sdk.Operation{}
	// Выбираем из общего среза oper оерации без кода FIGI -  это и есть все операции с деньгами за выбранный период.
	for _, op := range oper {if op.FIGI == "" {s = append(s, op)}}
	PrintLn(s)
