### ISSUE TITLE
Как получить список инструментов, которыми торговал за период? 

### ISSUE THREAD

**Issue by ILikeGoland** [TinkoffCreditSystems/invest-openapi-go-sdk#35]
Если бумагу сегодня купил и сегодня продал, и ее нет в портфеле, как после этого искать операции по ней? Перебор всех бумаг на предмет поиска по ним операций за период не эфективный путь и может загрузить сервер. Может быть есть более эффективные приемы решения этой проблемы?

**Comment by lightning95** [comment]
Вы ведь хотите искать операции по бумагам, "которые покупали раньше"?
Возможно Вам стоит завести структуру для хранения таких бумаг и время покупки/продажи

А потом искать операции в эти промежутки времени и по этим бумагам
https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/#/operations/get_operations

**Comment by lightning95** [comment]
"Figi инструмента для фильтрации" в сваггере - не обязательное поле, т.е если его не передавать (оставить пустым), то Вы получите все операции за указанный промежуток.

**Comment by ILikeGoland** [comment]
Мне не нужен отчет в свагере. Мне нужен отчет по всем операциям по всем бумагам за период в боевом режиме. Пробовал  без FIGI https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/issues/34  в боевом режиме. Он не дает всех операций

**Comment by NikitaMelnikov** [comment]
Если передавать figi = "" в метод https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/blob/master/rest_client.go#L143, то будут возвращаться операции по всем инструментам

**Comment by NikitaMelnikov** [comment]
> Мне не нужен отчет в свагере. Мне нужен отчет по всем операциям по всем бумагам за период в боевом режиме. 

Сваггер - просто UI для OpenApi, в нем вы можете посмотреть какие запросы отправляются и какой результат будет

**Comment by ILikeGoland** [comment]
Я конечно сегодня вечером попробую снова вместо FIGI ввести "", но  это уже делал и таким образом получал операции по движению денег на брокерском счете, но по всем операциям этот запрос с пустым полем FIGI в боевом режиме данных не выдает.   В свагере не пробовал поскольку это тестировать н прием данных можно и на бою.

**Comment by ILikeGoland** [comment]
Попробовал. Да действительно - сейчас при пустом FIGI получил все операции за период и нашел все бумаги, которые побывали в портфеле за период. Вопрос закрыт. Спасибо.
