### ISSUE TITLE
Периодические websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by a0s** [TinkoffCreditSystems/invest-openapi-go-sdk#38]
`can't read message: websocket: close 1006 (abnormal closure): unexpected EOF`

Сабж. Рвется довольно часто в течении торгового дня. Кто виноват, что делать? (с)

**Comment by necryin** [comment]
@a0s оставьте, пожалуйста, обращение в поддержку, они предадут всю нужную информацию и дальше мы сможем включить подробные логи по вашей активности в вебсокете. После этого также через поддержку сможем подебажить. От вас нужны будут логи на моменты таких ситуаций, IP.

**Comment by a0s** [comment]
Скорее всего,  тоже самое что и в https://github.com/TinkoffCreditSystems/invest-openapi/issues/126

**Comment by fxrlv** [comment]
переоткрывайте соединение и восстанавливайте подписки
это может быть обычный лаг сети, в этом случае никакой фикс ни на клиенте, ни на сервере не поможет

**Comment by AlexanderVolkovTCS** [comment]
Согласен с fxrlv - необходимо отлавливать такие ситуации и переоткрывать соединения.

**Comment by sukamenev** [comment]
@AlexanderVolkovTCS Проблема в том, что бот падает с этой ошибкой. Как можно её отловить, если программа вылетает?

Я сделал перезапуск программы, но это костыль.

Нужно сделать возможность отлавливать эту ошибку программно без вылета программы.

Вылетает примерно каждый час.
