### ISSUE TITLE
Пример примитивного робота

### ISSUE THREAD

**Issue by neshkeev** [TinkoffCreditSystems/invest-openapi-go-sdk#41]
Было бы здорово, если бы появился пример самого примитивного робота, который покупает бумагу, ждет, когда она вырастет немного, и продает ее. В частности, в приведенном примере непонятно как получить текущую цену инструмента. Есть два варианта:

1. подписаться на свечи  `*StreamingClient::SubscribeCandle` и мониторить цену закрытия
2. подписаться на стакан `*StreamingClient::SubscribeOrderbook` и смотреть по какой максимальной цене есть предложения на продажу

какой из них мне нужен?

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, для создания робота могут подойти оба варианта.
Буду благодарен за PR с подобным примером робота)
