### ISSUE TITLE
Streaming client не сообщает о прерывании интернет-соединения

### ISSUE THREAD

**Issue by neshkeev** [TinkoffCreditSystems/invest-openapi-go-sdk#42]
Я запустил следующий код:
```go
package main

import (
	"log"
	"math/rand"
	"os"
	"time"

	sdk "github.com/TinkoffCreditSystems/invest-openapi-go-sdk"
)

var token = "ENTER_TOKEN_HERE"

func main() {
	rand.Seed(time.Now().UnixNano())

	logger := log.New(os.Stdout, "[invest-openapi-go-sdk]", log.LstdFlags)

	client, err := sdk.NewStreamingClient(logger, token)
	if err != nil {
		log.Fatalln(err)
	}
	defer client.Close()

	go func() {
		err = client.RunReadLoop(func(event interface{}) error {
			return nil
		})
		if err != nil {
			log.Fatalln(err)
		}
	}()

	select {}
}

var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")

func requestID() string {
	b := make([]rune, 12)
	for i := range b {
		b[i] = letterRunes[rand.Intn(len(letterRunes))]
	}

	return string(b)
}
```
отключил интернет, но программа продолжила работать. Каким образом можно отслеживать события прерывания интернет-соединения?

**Comment by sgaynetdinov** [comment]
@neshkeev 
проверил, программа прерывается примерно через 3 минуты (отключал wifi)

P.S. для корректного вывода лога лучше заменить `log.Fatalln(err)` на `logger.Fatalln(err)`

**Comment by neshkeev** [comment]
3 минуты слишком долго, я ждал не более 20-30 секунд. Каким образом можно снизить время до обнаружении ошибки?

**Comment by sgaynetdinov** [comment]
контролировать timeout для чтения можно использую [SetReadLimit](https://pkg.go.dev/github.com/gorilla/websocket#Conn.SetReadLimit), для этого нужен доступ к полю `conn`
сейчас не вижу возможности им управлять, думаю без добавления нового функционала тут не обойтись

https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/blob/2d9f8ce7ce022aaf4f861157d4b83a25f7334352/streaming_client.go#L20-L25

**Comment by neshkeev** [comment]
Я, конечно, не знаю как там внутри все работает и почему выбрали 3 минуты по умолчанию, но мне кажется, что самое простое решение - это принудительно установить меньший интервал при создании `StreamingClient`
