### ISSUE TITLE
TradingStatus значение константы отличается от значения в ответе

### ISSUE THREAD

**Issue by NikolaySav** [TinkoffCreditSystems/invest-openapi-go-sdk#44]
`NormalTrading TradingStatus = "normal_trading"`

Значение отличается от полученного в ответе:
`"tradeStatus":"NormalTrading"`

Соответственно сравнить значение из статуса со значение константы не получается.

Полный ответ ниже:
`{"trackingId":"91e4cebe7fc44ec9","payload":{"figi":"BBG000B9XRY4","depth":10,"tradeStatus":"NormalTrading","minPriceIncrement":0.01,"lastPrice":120.01,"closePrice":119.26,"limitUp":120.85,"limitDown":118.96,"bids":[{"price":1.2E+2,"quantity":1657},{"price":119.99,"quantity":1029},{"price":119.98,"quantity":1493},{"price":119.97,"quantity":1201},{"price":119.96,"quantity":401},{"price":119.9,"quantity":117},{"price":119.8,"quantity":150},{"price":119.77,"quantity":1},{"price":119.7,"quantity":482},{"price":119.68,"quantity":7}],"asks":[{"price":120.01,"quantity":970},{"price":120.02,"quantity":3234},{"price":120.03,"quantity":1947},{"price":120.04,"quantity":1482},{"price":120.05,"quantity":3510},{"price":120.08,"quantity":8},{"price":120.1,"quantity":24},{"price":120.11,"quantity":16},{"price":120.12,"quantity":2},{"price":120.13,"quantity":3}]},"status":"Ok"}`

**Comment by NikolaySav** [comment]
https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/pull/45

**Comment by AlexanderVolkovTCS** [comment]
PR принят, спасибо!
