### ISSUE TITLE
Существует ли возможность установить TakeProfit / StopLoss ?

### ISSUE THREAD

**Issue by stdi0** [TinkoffCreditSystems/invest-openapi-go-sdk#47]
Добрый день!
Предусмотрена ли возможность установить TakeProfit/StopLoss?
Думал обойти это одновременным выставлением лимитной заявки, но у нее ограниченное время жизни.
Заранее спасибо за ответ!

**Comment by AlexanderVolkovTCS** [comment]
Добрый день, пока не реализовано.
