### ISSUE TITLE
Есть ли ограничения для подписки на свечи

### ISSUE THREAD

**Issue by goldenboy1991** [TinkoffCreditSystems/invest-openapi-go-sdk#48]
У вас доступно 6 TCP-соединений на одного пользователя. Существует ли ограничение для подписок на получение свечей(метод SubscribeCandle). Могу ли я подписаться на получение свечей по 1000 инструментам в разных таймфремах?

**Comment by necryin** [comment]
Программно ограничений нет. Но если клиент не будет успевать вычитывать данные то сервер будет закрывать такие коннекты.
