### ISSUE TITLE
Добавить примеры работы с go-sdk

### ISSUE THREAD

**Issue by ILikeGoland** [TinkoffCreditSystems/invest-openapi-go-sdk#5]
Разбираюсь с примером https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk
Пытаюсь в песочнице получить информацию об облигациях, которые находятся в моем портфеле. Пока безуспешно. 

Было бы здорово если бы не надо было рыть исходники в отладчике, чтобы догадаться - как получить подписку на свечи или информацию по торговому инструменту, а просто взять и написать по аналогии.  Но для этого нужны примеры обращения с объектами streamClient и restClient.

**Comment by BVV13** [comment]
Непонятно - как по коду FIGI или ISIN получить название эмитента.

**Comment by BVV13** [comment]
Было бы удобнее, если бы были примеры установки заявки и ее отмены. Не нашел на страничке https://tinkoffcreditsystems.github.io/invest-openapi/marketdata/  примеров установки лимитной и других типов заявок и их отмены или изменения. На страничке описания протокола "Rest" тоже нет ничего подобного.  Как программно установить заявку и снять ее? Не хватает примеров выполнения покупки или продажи по рынку.  
Возможно ли программно пополнить торговый счет с карты и вывести деньги и валюту с торговых счетов на карточные счета?

**Comment by BVV13** [comment]
Когда в свагере делаешь операцию покупки то код 
_ = stream.RunReadLoop(func(event interface{}) error {
		// Обработка сообщений
		Printf("event: %v %v\n", event, time.Now().String())
		return nil
	})
не фиксирует каких либо событий. Изменения в портфеле песочницы невозможно обработать.

**Comment by BVV13** [comment]
Удалось разобраться как устанавливать лимитные заявки :
     покупка
	lo1, err := api.LimitOrder(ctx, "BBG00GW0RM55", 29, "Buy", 200); if err != nil {log.Fatalln(err)}
     продажа 
	lo1, err := api.LimitOrder(ctx, "BBG00GW0RM55", 100, "Sell", 300); if err != nil {log.Fatalln(err)}
пока все работает

**Comment by necryin** [comment]
Поле Name в Instrument добавили. Примеры с описанием добавили в директорию examples

**Comment by BVV13** [comment]
Дайте адрес страницы - где можно посмотреть примеры с использованием поля "name"
Здесь https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/blob/master/examples/main.go опять ничего не нашел

**Comment by necryin** [comment]
Все методы market/* возвращают структуру Instrument. У этой структуры есть поле Name https://github.com/TinkoffCreditSystems/invest-openapi-go-sdk/blob/master/rest_domain.go#L94

**Comment by BVV13** [comment]
Оказывается надо было обновить SDK.
Спасибо. Все нашел

**Comment by ILikeGoland** [comment]
Вы имеете ввиду что надо туда писать или что этот вопрос закрыт и надо опять обновить сдк?

  
>Вторник, 31 декабря 2019, 13:40 +03:00 от George Kirilenko <notifications@github.com>:
> 
>Closed  #5 .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Виктор Викторович Бондаренко
7(962)974-5076
