### ISSUE TITLE
Метод restClient#Accounts выдаёт ошибку invalid token scopes

### ISSUE THREAD

**Issue by vodolaz095** [TinkoffCreditSystems/invest-openapi-go-sdk#59]
Данный метод [RestClient.Accounts](https://pkg.go.dev/github.com/Tinkoff/invest-openapi-go-sdk#RestClient.Accounts) выдаёт ошибку при недавно сгенерированном ключе c этой страницы https://www.tinkoff.ru/invest/settings/api/

Ошибка начала проявлятся 5 апреля. Сегодня, около 14 часов по Московскому времени срабатывала с данной версией библиотеки, как сказано в go.mod
```
github.com/Tinkoff/invest-openapi-go-sdk v0.6.2-0.20220224081737-ab5b2a40c0da
```

Минимальный пример кода:

```
package main

import (
	"context"
	"log"

	sdk "github.com/Tinkoff/invest-openapi-go-sdk"
)

const token = "этоНеСекретныйКлючДоступаКТорговомуСчётуХотяОнДолженТутБыть" 

func main() {
	rest := sdk.NewRestClient(token)

	accounts, err := rest.Accounts(context.Background())
	if err != nil {
		log.Fatalf("%s : while connecting to rest api", err)
	}
	for _, account := range accounts {
		log.Printf("Account %s %s is found!", account.ID, account.Type)
	}
}
```

Ошибка:
```
provider post: provider do: TrackingID: 9dfcf1ae343507ec, Status: Error, Message: Invalid token scopes, Code: GATEWAYREQUESTDATA_ERROR, Hint:  : while connecting to rest api
```
Завтра утром я попробую ещё раз воспроизвести ошибку, надеюсь, я смог помочь.
C уважением, Анатолий.

**Comment by vodolaz095** [comment]
Я запускал код на дистрибутиве Fedora Linux 34 с компилятором из репозиториев дистрибутива:
```
[vodolaz095@steel data]$ go version
go version go1.16.15 linux/amd64
```

Раньше (до 5 апреля) метод RestClient#Accounts работал... мне кажется, что именно в генерации токенов что-то не то...

**Comment by AlexanderVolkovTCS** [comment]
Убедитесь, пожалуйста, что токен выпускается без ограничений (не readonly и не к конкретному счету). 
Токены с ограничениями работают только в новом апи https://github.com/Tinkoff/investAPI.

**Comment by vodolaz095** [comment]
Вечером 6 апреля 2022 года мы сделали новые токены (полный доступ ко всем счетам), 
и эти версии версии библиотеки `invest-openapi-go-sdk`  (как написанно в `go.mod`)

```
github.com/Tinkoff/invest-openapi-go-sdk v0.6.2-0.20220224081737-ab5b2a40c0da
```

```
github.com/TinkoffCreditSystems/invest-openapi-go-sdk v0.6.1
```

работают без ошибок.

То есть, скорее всего ошибка была не в коде библиотеки, а при генерации\валидации токена на стороне API.

У меня есть мой личный, но уже отозванный токен (с которым проявлялась описанная прежде ошибка), 
я бы мог послать его через мессенджер банка, если это поможет прояснить ситуацию.
Возможно, его как то можно у вас расшифровать, и посмотреть, что в нём сгенерировалось неправильно.
