### ISSUE TITLE
30014 Превышен максимальный период запроса для данного интервала свечи.

### ISSUE THREAD

**Issue by AleksGelvides** [TinkoffCreditSystems/invest-openapi-go-sdk#63]
Добрый день. Изо всех сил пытаюсь получить историю котировок за 1 год, на 5 минутном таймфрейме и получаю ошибку.

Вот мой код: 
``
var histories = api.getMarketDataService()
                .getCandlesSync(quote.getFIGI(), Instant.now().minus(12, ChronoUnit.DAYS), Instant.now(), CandleInterval.CANDLE_INTERVAL_5_MIN)
                .stream().map(QuoteBarDTO::createQuote).toList();
``
При этом, если я укажу минус 1 день, я получу пустой массив. Но оно и так понятно, сейчас выходные и данных нет.
Если я укажу 3 дня, что бы получить "всю пятницу", я снова получаю ошибку периода.
Помогите пожалуйста понять как именно это работает.

Полный код ошибки:
`30014 Превышен максимальный период запроса для данного интервала свечи. Укажите корректный интервал. tracking_id 3e7232fae7b7ad715d42610b6d50fc07`

**Comment by AlexanderVolkovTCS** [comment]
Добрый день! 
На 5-минутном таймфрейме максимальный диапазон запрашиваемых дат - 1 сутки.

Вам надо в цикле перебрать все даты и запросить за каждый день с 0:00 до 23:59

Кстати рекомендуем переходить на новую версию API https://github.com/Tinkoff/investAPI/

**Comment by AleksGelvides** [comment]
Спасибо! Только что перебрал. Всё получилось)
