### ISSUE TITLE
bad response to ... code=403 - на любой запрос по Rest 

### ISSUE THREAD

**Issue by microup** [TinkoffCreditSystems/invest-openapi-go-sdk#64]
Если взять пример из examples/main.go и попробовать выполнить любой запрос через Rest методы на получение часовых свечей:

`candles, err := r.client.Candles(ctx, time.Now().AddDate(0, 0, -1), time.Now(), sdk.CandleInterval1Hour, "BBG005DXJS36")`

или инструментов по тикеру.... 

`instruments, err := r.client.InstrumentByTicker(r.ctx, ticket)`

то любой из этих запросов всегда возвращает ошибку.....

`bad response to https://api-invest.tinkoff.ru/openapi/.............................. code=403, body=`

В чем может быть проблема? Как ее решить?

**Comment by maniack** [comment]
Аналогичная проблема "bad response to https://api-invest.tinkoff.ru/openapi/user/accounts code=403, body=" в https://github.com/maksim77/tinkoff_exporter/

**Comment by AlexanderVolkovTCS** [comment]
403 - ошибка авторизации. Проверьте или перевыпустите токен (срок жизни токена - 3 месяца с даты последнего использования). Плюс отмечу, что для старой версии api, на которой работает этот СДК, возможно использование только токенов с полным доступом по всем счетам. 

Если перевыпуск токена не поможет, то прошу переоткрыть issue

**Comment by microup** [comment]
Пробовал создавать новые токены для песочницы и с полным доступом. Результат всегда один: ошибка 403.
